name: "Assert Actual Is Expected"
branding:
  icon: "target"
  color: "green"
description: "Write tests in GitHub Workflows for integration tests and build pipelines"
author: "Samuel Ryan <sam@samryan.co.uk>"
inputs:
  assertion:
    description: "Name of the assertion to run against value"
    required: true
  expected:
    description: "Value the assertion is looking for"
    required: false
  actual:
    description: "Dynamic value to test against"
    required: false
  type:
    description: "Javascript data type that actual and expected will be cast to"
    default: "string"
    required: true
  each:
    description: "Parse multi-line `actual` into many values and assert against each"
    default: "false"
    required: false
  local-path:
    description: "Path to assertions on the runner's filesystem"
    default: "${{ github.workspace }}"
    required: true
  error-on-fail:
    description: "Report error in step when assertion fails"
    default: "true"
    required: true
  error-message:
    description: "Error message to output when assertion fails"
    required: false
  convert-empty-to-null:
    description: "Convert empty input values to null"
    default: "true"
    required: true
outputs:
  message:
    description: "Human readable result of the assertion"
  pass:
    description: "Boolean describing whether the assertion passed"
  passed:
    description: "Boolean describing whether the assertion passed"
  failed:
    description: "Boolean describing whether the assertion failed"
  error:
    description: "Error message (if any) that has been output to the log"
runs:
  using: "node16"
  main: "dist/index.js"
